version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: gifter
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 54320:8080