version: '3'

tasks:
  run:
    cmds:
      - go run main.go
    env:
      POSTGRES_URL: postgres://postgres:example@localhost:5432/gifter

  dev:
    cmds:
      - go run main.go
    env:
      POSTGRES_URL: postgres://postgres:example@localhost:5432/gifter
